// Hexis SKINTAC HX20000 & HX30000 Series - REAL Complete Color Dataset
// Updated with actual Hexis product codes and names from hexisamericas.com

const STORAGE_BASE = "https://abgevylqeazbydrtovzp.supabase.co/storage/v1/object/public/swatches/hexis";

export const hexisColors = [
  // === HX30 SUPER CHROME GLOSS SERIES ===
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Silver Gloss", code: "HX30SCH01B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#C0C0C0", media_url: `${STORAGE_BASE}/HX30SCH01B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Red Gloss", code: "HX30SCH02B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#E30613", media_url: `${STORAGE_BASE}/HX30SCH02B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Titanium Gloss", code: "HX30SCH03B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#707070", media_url: `${STORAGE_BASE}/HX30SCH03B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Green Gloss", code: "HX30SCH04B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#00FF00", media_url: `${STORAGE_BASE}/HX30SCH04B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Blue Gloss", code: "HX30SCH05B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#0000FF", media_url: `${STORAGE_BASE}/HX30SCH05B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Purple Gloss", code: "HX30SCH06B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#800080", media_url: `${STORAGE_BASE}/HX30SCH06B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Gold Gloss", code: "HX30SCH07B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#FFD700", media_url: `${STORAGE_BASE}/HX30SCH07B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Orange Gloss", code: "HX30SCH08B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#FF4500", media_url: `${STORAGE_BASE}/HX30SCH08B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Turquoise Gloss", code: "HX30SCH09B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#40E0D0", media_url: `${STORAGE_BASE}/HX30SCH09B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Pink Gloss", code: "HX30SCH10B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#FF69B4", media_url: `${STORAGE_BASE}/HX30SCH10B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Light Blue Gloss", code: "HX30SCH11B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#87CEEB", media_url: `${STORAGE_BASE}/HX30SCH11B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Rose Gold Gloss", code: "HX30SCH12B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#B76E79", media_url: `${STORAGE_BASE}/HX30SCH12B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Ebonite Black Gloss", code: "HX30SCH13B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#1C1C1C", media_url: `${STORAGE_BASE}/HX30SCH13B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Lemon Green Gloss", code: "HX30SCH14B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#32CD32", media_url: `${STORAGE_BASE}/HX30SCH14B.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Arabica Copper Gloss", code: "HX30SCH15B", finish: "Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#8B4513", media_url: `${STORAGE_BASE}/HX30SCH15B.png` },

  // === HX30 SUPER CHROME SATIN SERIES ===
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Silver Satin", code: "HX30SCH01S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#A9A9A9", media_url: `${STORAGE_BASE}/HX30SCH01S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Red Satin", code: "HX30SCH02S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#DC143C", media_url: `${STORAGE_BASE}/HX30SCH02S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Titanium Satin", code: "HX30SCH03S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#616161", media_url: `${STORAGE_BASE}/HX30SCH03S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Green Satin", code: "HX30SCH04S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#00CC00", media_url: `${STORAGE_BASE}/HX30SCH04S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Blue Satin", code: "HX30SCH05S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#0066CC", media_url: `${STORAGE_BASE}/HX30SCH05S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Purple Satin", code: "HX30SCH06S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#6A0DAD", media_url: `${STORAGE_BASE}/HX30SCH06S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Gold Satin", code: "HX30SCH07S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#D4AF37", media_url: `${STORAGE_BASE}/HX30SCH07S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Orange Satin", code: "HX30SCH08S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#FF6600", media_url: `${STORAGE_BASE}/HX30SCH08S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Turquoise Satin", code: "HX30SCH09S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#30D5C8", media_url: `${STORAGE_BASE}/HX30SCH09S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Pink Satin", code: "HX30SCH10S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#FF1493", media_url: `${STORAGE_BASE}/HX30SCH10S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Light Blue Satin", code: "HX30SCH11S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#6EB3F1", media_url: `${STORAGE_BASE}/HX30SCH11S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Rose Gold Satin", code: "HX30SCH12S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#C9A86C", media_url: `${STORAGE_BASE}/HX30SCH12S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Lemon Green Satin", code: "HX30SCH14S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#4CBB17", media_url: `${STORAGE_BASE}/HX30SCH14S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Arabica Copper Satin", code: "HX30SCH15S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#8B4513", media_url: `${STORAGE_BASE}/HX30SCH15S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Scarlet Fever Red Satin", code: "HX30SCH16S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#FF2400", media_url: `${STORAGE_BASE}/HX30SCH16S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Rigel Blue Satin", code: "HX30SCH17S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#1E90FF", media_url: `${STORAGE_BASE}/HX30SCH17S.png` },
  { manufacturer: "Hexis", series: "HX30 Super Chrome", name: "Super Chrome Canopy Green Satin", code: "HX30SCH18S", finish: "Satin Chrome", color_type: "chrome", metallic: false, pearl: false, chrome: true, ppf: false, hex: "#013220", media_url: `${STORAGE_BASE}/HX30SCH18S.png` },

  // === HX30 CARBON SERIES ===
  { manufacturer: "Hexis", series: "HX30 Carbon", name: "Black Carbon Gloss", code: "HX30CA890B", finish: "Carbon", color_type: "textured", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#1C1C1C", media_url: `${STORAGE_BASE}/HX30CA890B.png` },
  { manufacturer: "Hexis", series: "HX30 Carbon", name: "Petroleum Black Carbon Gloss", code: "HX30CANPEB", finish: "Carbon", color_type: "textured", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#2A2A2A", media_url: `${STORAGE_BASE}/HX30CANPEB.png` },
  { manufacturer: "Hexis", series: "HX30 Carbon", name: "Raven Black Carbon Gloss", code: "HX30CANCOB", finish: "Carbon", color_type: "textured", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#212121", media_url: `${STORAGE_BASE}/HX30CANCOB.png` },
  { manufacturer: "Hexis", series: "HX30 Carbon", name: "Black Forged Carbon Satin", code: "HX30CAF89S", finish: "Carbon", color_type: "textured", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#1A1A1A", media_url: `${STORAGE_BASE}/HX30CAF89S.png` },
  { manufacturer: "Hexis", series: "HX30 Carbon", name: "Honeycomb Black Satin", code: "HX30HC889S", finish: "Carbon", color_type: "textured", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#181818", media_url: `${STORAGE_BASE}/HX30HC889S.png` },
  { manufacturer: "Hexis", series: "HX30 Carbon", name: "FGrain Leather Black Gloss", code: "HX30PG889B", finish: "Carbon", color_type: "textured", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#1E1E1E", media_url: `${STORAGE_BASE}/HX30PG889B.png` },
  { manufacturer: "Hexis", series: "HX30 Carbon", name: "Carbon Pearl White Gloss", code: "HX30CABPEB", finish: "Carbon", color_type: "textured", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#F5F5F5", media_url: `${STORAGE_BASE}/HX30CABPEB.png` },
  { manufacturer: "Hexis", series: "HX30 Carbon", name: "Graphite Grey Carbon Gloss", code: "HX30CAGGRB", finish: "Carbon", color_type: "textured", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#474747", media_url: `${STORAGE_BASE}/HX30CAGGRB.png` },
  { manufacturer: "Hexis", series: "HX30 Carbon", name: "Carbon One Gloss", code: "HX30CAONEB", finish: "Carbon", color_type: "textured", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#232323", media_url: `${STORAGE_BASE}/HX30CAONEB.png` },

  // === HX30 SPECIAL EFFECTS ===
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Nacre White Gloss", code: "HX30BNCB", finish: "Gloss", color_type: "pearl", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#FAFAFA", media_url: `${STORAGE_BASE}/HX30BNCB.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Pearl White Gloss", code: "HX30BPEB", finish: "Gloss", color_type: "pearl", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#F8F8F8", media_url: `${STORAGE_BASE}/HX30BPEB.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Redcurrant Red Gloss", code: "HX30RGOB", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#CC0000", media_url: `${STORAGE_BASE}/HX30RGOB.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Redcurrant Red Matte", code: "HX30RGOM", finish: "Matte", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#B30000", media_url: `${STORAGE_BASE}/HX30RGOM.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Chameleon Grey Gloss", code: "HX30G446B", finish: "Chameleon", color_type: "color_shift", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#6B6B6B", media_url: `${STORAGE_BASE}/HX30G446B.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Neon Blue Gloss", code: "HX30BNEB", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#0000FF", media_url: `${STORAGE_BASE}/HX30BNEB.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Boston Green Matte", code: "HX30VBOM", finish: "Matte", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#00CC66", media_url: `${STORAGE_BASE}/HX30VBOM.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Austral Sea Iridescent Gloss", code: "HX30IAMB", finish: "Iridescent", color_type: "color_shift", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#5F9EA0", media_url: `${STORAGE_BASE}/HX30IAMB.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Boreal Forest Iridescent Gloss", code: "HX30IFBB", finish: "Iridescent", color_type: "color_shift", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#228B22", media_url: `${STORAGE_BASE}/HX30IFBB.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Golden Black Matte", code: "HX30N71M", finish: "Matte", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#444400", media_url: `${STORAGE_BASE}/HX30N71M.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "White Rainbow Gloss", code: "HX30RW002B", finish: "Rainbow", color_type: "color_shift", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#F0F0F0", media_url: `${STORAGE_BASE}/HX30RW002B.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Meteorite Grey Rainbow Gloss", code: "HX30RW990B", finish: "Rainbow", color_type: "color_shift", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#4A4A4A", media_url: `${STORAGE_BASE}/HX30RW990B.png` },
  { manufacturer: "Hexis", series: "HX30 Special Effects", name: "Coal Black Rainbow Gloss", code: "HX30RW889B", finish: "Rainbow", color_type: "color_shift", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#292929", media_url: `${STORAGE_BASE}/HX30RW889B.png` },

  // === HX30 BRUSHED ALUMINUM ===
  { manufacturer: "Hexis", series: "HX30 Brushed", name: "Brushed Alu Gloss", code: "HX30BASILB", finish: "Brushed", color_type: "textured", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#C0C0C0", media_url: `${STORAGE_BASE}/HX30BASILB.png` },
  { manufacturer: "Hexis", series: "HX30 Brushed", name: "Brush Alu Anthracite Grey Gloss", code: "HX30BAGANB", finish: "Brushed", color_type: "textured", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#3E3E3E", media_url: `${STORAGE_BASE}/HX30BAGANB.png` },

  // === HX20000 GLOSS SOLID COLORS ===
  { manufacturer: "Hexis", series: "HX20000", name: "Deep Black", code: "HX20890B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#000000", media_url: `${STORAGE_BASE}/HX20890B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Polar White", code: "HX20001B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#F0F0F0", media_url: `${STORAGE_BASE}/HX20001B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Bright Red", code: "HX20186B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#E30613", media_url: `${STORAGE_BASE}/HX20186B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Racing Red", code: "HX20485B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#B92026", media_url: `${STORAGE_BASE}/HX20485B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Burgundy Red", code: "HX20505B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#6A001A", media_url: `${STORAGE_BASE}/HX20505B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Daffodil Yellow", code: "HX20109B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#F7E51B", media_url: `${STORAGE_BASE}/HX20109B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Golden Yellow", code: "HX20123B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#FCD100", media_url: `${STORAGE_BASE}/HX20123B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Mandarin Orange", code: "HX20165B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#F26522", media_url: `${STORAGE_BASE}/HX20165B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Saffron Orange", code: "HX20354B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#F7931E", media_url: `${STORAGE_BASE}/HX20354B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Apple Green", code: "HX20375B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#66B032", media_url: `${STORAGE_BASE}/HX20375B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Grass Green", code: "HX20348B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#578B40", media_url: `${STORAGE_BASE}/HX20348B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Forest Green", code: "HX20336B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#004B38", media_url: `${STORAGE_BASE}/HX20336B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Firmament Blue", code: "HX20293B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#0071A7", media_url: `${STORAGE_BASE}/HX20293B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Fjord Blue", code: "HX20219B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#4682B4", media_url: `${STORAGE_BASE}/HX20219B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Night Blue", code: "HX20303B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#1F2B44", media_url: `${STORAGE_BASE}/HX20303B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Sky Blue", code: "HX20446B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#009FE3", media_url: `${STORAGE_BASE}/HX20446B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Violet", code: "HX20008B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#462E5F", media_url: `${STORAGE_BASE}/HX20008B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Fuchsia Pink", code: "HX20518B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#E04E8B", media_url: `${STORAGE_BASE}/HX20518B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Medium Gray", code: "HX20445B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#6D7073", media_url: `${STORAGE_BASE}/HX20445B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Nardo Gray", code: "HX20423B", finish: "Gloss", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#5C6268", media_url: `${STORAGE_BASE}/HX20423B.png` },

  // === HX20000 GLOSS METALLIC COLORS ===
  { manufacturer: "Hexis", series: "HX20000", name: "Black Metal", code: "HX20889B", finish: "Gloss", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#1B1B1B", media_url: `${STORAGE_BASE}/HX20889B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Titanium Grey Metal", code: "HX20TITB", finish: "Gloss", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#5D6063", media_url: `${STORAGE_BASE}/HX20TITB.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Silver Metal", code: "HX20877B", finish: "Gloss", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#B3B3B3", media_url: `${STORAGE_BASE}/HX20877B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Gold Metal", code: "HX20871B", finish: "Gloss", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#B7950B", media_url: `${STORAGE_BASE}/HX20871B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Copper Metal", code: "HX20COPB", finish: "Gloss", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#995740", media_url: `${STORAGE_BASE}/HX20COPB.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Blue Metal", code: "HX20227B", finish: "Gloss", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#003366", media_url: `${STORAGE_BASE}/HX20227B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Racing Blue Metal", code: "HX20207B", finish: "Gloss", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#003366", media_url: `${STORAGE_BASE}/HX20207B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Green Metal", code: "HX20360B", finish: "Gloss", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#006633", media_url: `${STORAGE_BASE}/HX20360B.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Red Metal", code: "HX20186M", finish: "Gloss", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#B02026", media_url: `${STORAGE_BASE}/HX20186M.png` },

  // === HX30000 SATIN COLORS ===
  { manufacturer: "Hexis", series: "HX30000", name: "Satin Black", code: "HX30890B", finish: "Satin", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#212121", media_url: `${STORAGE_BASE}/HX30890B.png` },
  { manufacturer: "Hexis", series: "HX30000", name: "Satin White", code: "HX30001B", finish: "Satin", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#E8E8E8", media_url: `${STORAGE_BASE}/HX30001B.png` },
  { manufacturer: "Hexis", series: "HX30000", name: "Satin Nardo Grey", code: "HX30423S", finish: "Satin", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#5E6266", media_url: `${STORAGE_BASE}/HX30423S.png` },
  { manufacturer: "Hexis", series: "HX30000", name: "Satin Titanium Grey Metal", code: "HX30TITS", finish: "Satin", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#5F6266", media_url: `${STORAGE_BASE}/HX30TITS.png` },
  { manufacturer: "Hexis", series: "HX30000", name: "Satin Pearl White", code: "HX30BPEB", finish: "Satin", color_type: "pearl", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#E8E8E8", media_url: `${STORAGE_BASE}/HX30BPEB.png` },

  // === MATTE COLORS ===
  { manufacturer: "Hexis", series: "HX20000", name: "Matte Black", code: "HX20NEPM", finish: "Matte", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#212121", media_url: `${STORAGE_BASE}/HX20NEPM.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Matte White", code: "HX20001M", finish: "Matte", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#E6E6E6", media_url: `${STORAGE_BASE}/HX20001M.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Matte Dark Grey", code: "HX20G01M", finish: "Matte", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#414141", media_url: `${STORAGE_BASE}/HX20G01M.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Matte Charcoal Metal", code: "HX20CHAB", finish: "Matte", color_type: "metallic", metallic: true, pearl: false, chrome: false, ppf: false, hex: "#363A3D", media_url: `${STORAGE_BASE}/HX20CHAB.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Matte Military Green", code: "HX20MILM", finish: "Matte", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#4B5242", media_url: `${STORAGE_BASE}/HX20MILM.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Matte Khaki Green", code: "HX20N71M", finish: "Matte", color_type: "solid", metallic: false, pearl: false, chrome: false, ppf: false, hex: "#5C5C47", media_url: `${STORAGE_BASE}/HX20N71M.png` },

  // === SPECIAL EFFECTS ===
  { manufacturer: "Hexis", series: "HX20000", name: "Chameleon Blue Purple", code: "HX20NCHR", finish: "Chameleon", color_type: "color_shift", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#4B0082", media_url: `${STORAGE_BASE}/HX20NCHR.png` },
  { manufacturer: "Hexis", series: "HX20000", name: "Chameleon Green Gold", code: "HX20NCGR", finish: "Chameleon", color_type: "color_shift", metallic: false, pearl: true, chrome: false, ppf: false, hex: "#605C3B", media_url: `${STORAGE_BASE}/HX20NCGR.png` },
];

export default hexisColors;
